### ISSUE TITLE
A error about "float128"

### ISSUE THREAD

**Issue by ChengWan9** [CHPGenetics/COMPOSITE#2]
Thanks for your great work! But when I run the code on the RNA modality, there seems a bug as the following:
![image](https://github.com/CHPGenetics/COMPOSITE/assets/143673887/cdc29e08-9eef-420f-9a00-0a226098a364)

**Comment by ChengWan9** [comment]
And when I use the demo data you give, I encounter the issue with Multiomics.composite_multiomics:
![image](https://github.com/CHPGenetics/COMPOSITE/assets/143673887/a5ef067c-fd4d-46da-ae95-acfe0279a798)

**Comment by CHPGenetics** [comment]
Thank you for the feedback! Are you using Windows OS? These two issues are both likely caused by the incompatibility of some Numpy features on Windows: https://github.com/pymc-devs/pymc-resources/issues/90. For now, we recommend Windows users to use our web-based application at: https://shiny.crc.pitt.edu/shinyproj_composite/

**Comment by ChengWan9** [comment]
> Thank you for the feedback! Are you using Windows OS? These two issues are both likely caused by the incompatibility of some Numpy features on Windows: [pymc-devs/pymc-resources#90](https://github.com/pymc-devs/pymc-resources/issues/90). For now, we recommend Windows users to use our web-based application at: https://shiny.crc.pitt.edu/shinyproj_composite/

Yes，I am using Windows OS and when I use Ubuntu, there is no error. Thanks for your reply!
