### ISSUE TITLE
list of dependencies?

### ISSUE THREAD

**Issue by nick-youngblut** [CHPGenetics/COMPOSITE#4]
Where are the list of dependencies and required version for COMPOSITE? I don't see a `requirements.txt`, ` pyproject.toml`, `conda_env.yaml`, etc. in the codebase.

**Comment by CHPGenetics** [comment]
Thank you for your question!

A list of dependencies of COMPOSITE can be found at the first code chunk of https://github.com/CHPGenetics/COMPOSITE/blob/main/experiments/COMPOSITE_DOGMA_results.ipynb  

Since the dependencies are several basic python packages, different versions should not significantly impact the results.
